-- 코드를 입력하세요
-- 보호기간 = 입양일 - 보호시작일
SELECT *
FROM (SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS INNER JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY OUTS.DATETIME - INS.DATETIME DESC) JOINED
WHERE ROWNUM <= 2;