-- 코드를 입력하세요
-- 입양을 못간 동물 오래된 3마리의 이름, 보호시작일
SELECT JOINED.NAME, JOINED.DATETIME
FROM
(SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS INS
LEFT OUTER JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.ANIMAL_ID IS NULL
ORDER BY INS.DATETIME ASC) JOINED
WHERE ROWNUM <= 3;