-- 코드를 입력하세요
-- 보호 시작일보다 입양일이 더 빠른 아이디와 이름을 조회
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS 
INNER JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME ASC;; 